# vim: ft=config

include ./themes/tomorrow_night.conf

cursor_shape         block
font_family          JetBrains Mono
font_size            13
window_padding_width 12
background_opacity   0.95
disable_ligatures    always

enabled_layouts tall:bias=50,vertical

close_on_child_death yes
enable_audio_bell    no
linux_display_server x11

kitty_mod ctrl+shift

map ctrl+shift+; load_config_file
map kitty_mod+enter launch --cwd=current
map ctrl+shift+t new_tab_with_cwd

map ctrl+shift+g show_last_command_output

shell_integration no-cursor
