font_family JetBrainsMono Nerd Font
font_size 15
modify_font cell_height +8px

# dynamic_background_opacity no
# background_opacity 0.95
# background_blur 64

window_padding_width 12
macos_titlebar_color #323639

shell_integration no-cursor
confirm_os_window_close 0

enabled_layouts tall:bias=50;full_size=1;mirrored=false, vertical

macos_option_as_alt yes

kitty_mod cmd
map kitty_mod+t new_tab_with_cwd
map kitty_mod+n new_os_window_with_cwd
map kitty_mod+enter launch --cwd=current
map kitty_mod+shift+l next_layout
map kitty_mod+shift+f move_window_forward
map cmd+w close_window

include theme.conf
