font_family JetBrains Mono
font_size   15
modify_font cell_height +8px

window_padding_width 12

enabled_layouts tall:bias=50;full_size=1;mirrored=false, vertical

shell_integration no-cursor

confirm_os_window_close 0

macos_option_as_alt yes
kitty_mod cmd
map kitty_mod+shift+t new_tab_with_cwd
map kitty_mod+shift+n new_os_window_with_cwd
map kitty_mod+shift+enter launch --cwd=current

map kitty_mod+shift+l next_layout
map kitty_mod+shift+f move_window_forward

# map cmd+w close_window

# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME
