[global]
# Your Spotify account name.
username = "carlisecp01"

# Changes to this file are ignored using:
# `git update-index --skip-worktree default_values.txt`
# `git update-index --no-skip-worktree default_values.txt`
# Show skipped files:
# `git ls-files -v . | grep ^S`
password = "<YOUR_PASSWORD_HERE>"

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name = "Carlos's Laptop"

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, t_v,
device_type = "computer"
