# vim: ft=config

backend = "glx"

# Shadows
shadow = true;
shadow-radius: 20;
shadow-opacity = .5;
shadow-offset-x = -20;
shadow-offset-y = -20;

# Blur
blur:
{
	method = "dual_kawase";
	size = 20;
	deviation = 10.0;
};

blur-background-exclude = [
	"class_g = 'slop'",
];

wintypes:
{
	tooltip = {
		fade = true;
		shadow = false;
		opacity = 0.75;
		focus = true;
		full-shadow = false;
	};
	dock = {
		shadow = false;
		clip-shadow-above = true;
	};
	dnd = { shadow = false; };
};
